"""create expenses table

Revision ID: 715f5542bda3
Revises: f7cabbc606c8
Create Date: 2026-01-28 10:35:31.257151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.core.config import settings

# revision identifiers, used by Alembic.
revision: str = '715f5542bda3'
down_revision: Union[str, Sequence[str], None] = 'f7cabbc606c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SCHEMA = settings.DATABASE_SCHEMA


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('expense_type', sa.Enum('RECURRING', 'ONE_TIME', name='expensetype'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('BRL', 'USD', name='currency'), nullable=False),
    sa.Column('value_brl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('exchange_rate_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periodicity', sa.Enum('MONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'ANNUAL', name='periodicity'), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'BOLETO', 'PIX', 'TRANSFER', name='paymentmethod'), nullable=False),
    sa.Column('payment_identifier', sa.String(length=50), nullable=True),
    sa.Column('contracted_plan', sa.String(length=100), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('evidence_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'ACTIVE', 'CANCELLATION_REQUESTED', 'CANCELLED', 'SUSPENDED', 'MIGRATED', name='expensestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], [f'{SCHEMA}.users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], [f'{SCHEMA}.categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], [f'{SCHEMA}.companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], [f'{SCHEMA}.departments.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], [f'{SCHEMA}.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA
    )
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema=SCHEMA)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema=SCHEMA)
    op.alter_column('departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema=SCHEMA)
    op.drop_constraint(op.f('departments_company_id_fkey'), 'departments', type_='foreignkey', schema=SCHEMA)
    op.create_foreign_key(None, 'departments', 'companies', ['company_id'], ['id'], source_schema=SCHEMA, referent_schema=SCHEMA)
    op.drop_constraint(op.f('user_departments_department_id_fkey'), 'user_departments', type_='foreignkey', schema=SCHEMA)
    op.drop_constraint(op.f('user_departments_user_id_fkey'), 'user_departments', type_='foreignkey', schema=SCHEMA)
    op.create_foreign_key(None, 'user_departments', 'users', ['user_id'], ['id'], source_schema=SCHEMA, referent_schema=SCHEMA)
    op.create_foreign_key(None, 'user_departments', 'departments', ['department_id'], ['id'], source_schema=SCHEMA, referent_schema=SCHEMA)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema=SCHEMA)
    op.drop_index(op.f('ix_users_email'), table_name='users', schema=SCHEMA)
    op.create_index(op.f(f'ix_{SCHEMA}_users_email'), 'users', ['email'], unique=True, schema=SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f(f'ix_{SCHEMA}_users_email'), table_name='users', schema=SCHEMA)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, schema=SCHEMA)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema=SCHEMA)
    op.drop_constraint(None, 'user_departments', schema=SCHEMA, type_='foreignkey')
    op.drop_constraint(None, 'user_departments', schema=SCHEMA, type_='foreignkey')
    op.create_foreign_key(op.f('user_departments_user_id_fkey'), 'user_departments', 'users', ['user_id'], ['id'], source_schema=SCHEMA, referent_schema=SCHEMA)
    op.create_foreign_key(op.f('user_departments_department_id_fkey'), 'user_departments', 'departments', ['department_id'], ['id'], source_schema=SCHEMA, referent_schema=SCHEMA)
    op.drop_constraint(None, 'departments', schema=SCHEMA, type_='foreignkey')
    op.create_foreign_key(op.f('departments_company_id_fkey'), 'departments', 'companies', ['company_id'], ['id'], source_schema=SCHEMA, referent_schema=SCHEMA)
    op.alter_column('departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema=SCHEMA)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema=SCHEMA)
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema=SCHEMA)
    op.drop_table('expenses', schema=SCHEMA)
    # ### end Alembic commands ###
