import type {
  User,
  Company,
  Department,
  Category,
  Expense,
  ExpenseValidation,
  Alert,
  DashboardStats,
} from '@/types';

// Mock Users (IDs como string para compatibilidade com API)
export const mockUsers: User[] = [
  { id: '1', name: 'Admin Finance', email: 'admin@nitro.com', role: 'finance_admin', phone: '(11) 99999-0001', is_active: true, departments: [] },
  {
    id: '2',
    name: 'Carlos Leader',
    email: 'leader@nitro.com',
    role: 'leader',
    phone: '(11) 99999-0002',
    is_active: true,
    departments: [{ id: '1', name: 'Tecnologia', company_id: '1', is_active: true }],
  },
  {
    id: '3',
    name: 'Maria User',
    email: 'user@nitro.com',
    role: 'user',
    phone: '(11) 99999-0003',
    is_active: true,
    departments: [{ id: '1', name: 'Tecnologia', company_id: '1', is_active: true }],
  },
];

export const mockCompanies: Company[] = [
  { id: '1', name: 'Nitro Corp', is_active: true },
  { id: '2', name: 'Nitro Digital', is_active: true },
  { id: '3', name: 'Nitro Labs', is_active: false },
];

export const mockDepartments: Department[] = [
  { id: '1', name: 'Tecnologia', company_id: '1', company: mockCompanies[0], is_active: true },
  { id: '2', name: 'Marketing', company_id: '1', company: mockCompanies[0], is_active: true },
  { id: '3', name: 'RH', company_id: '1', company: mockCompanies[0], is_active: true },
  { id: '4', name: 'Desenvolvimento', company_id: '2', company: mockCompanies[1], is_active: true },
  { id: '5', name: 'Design', company_id: '2', company: mockCompanies[1], is_active: true },
];

export const mockCategories: Category[] = [
  { id: '1', name: 'Software & SaaS', is_active: true },
  { id: '2', name: 'Infraestrutura', is_active: true },
  { id: '3', name: 'Marketing Digital', is_active: true },
  { id: '4', name: 'Consultoria', is_active: true },
  { id: '5', name: 'Treinamentos', is_active: false },
];

export const mockExpenses: Expense[] = [
  {
    id: '1',
    service_name: 'AWS Cloud Services',
    description: 'Infraestrutura de cloud computing',
    expense_type: 'recurring',
    category_id: '2',
    category: mockCategories[1],
    company_id: '1',
    company: mockCompanies[0],
    department_id: '1',
    department: mockDepartments[0],
    owner_id: '2',
    owner: mockUsers[1],
    approver_id: '1',
    value: 15000,
    currency: 'USD',
    value_brl: 75000,
    periodicity: 'monthly',
    renewal_date: '2025-02-15',
    payment_method: 'credit_card',
    status: 'active',
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
  {
    id: '2',
    service_name: 'Slack Business+',
    description: 'Comunicação interna da equipe',
    expense_type: 'recurring',
    category_id: '1',
    category: mockCategories[0],
    company_id: '1',
    company: mockCompanies[0],
    department_id: '1',
    department: mockDepartments[0],
    owner_id: '2',
    owner: mockUsers[1],
    approver_id: '1',
    value: 2500,
    currency: 'BRL',
    value_brl: 2500,
    periodicity: 'monthly',
    renewal_date: '2025-03-01',
    payment_method: 'credit_card',
    user_count: 50,
    status: 'active',
    created_at: '2024-02-01',
    updated_at: '2024-02-01',
  },
  {
    id: '3',
    service_name: 'Google Workspace',
    description: 'Email corporativo e ferramentas de produtividade',
    expense_type: 'recurring',
    category_id: '1',
    category: mockCategories[0],
    company_id: '1',
    company: mockCompanies[0],
    department_id: '3',
    department: mockDepartments[2],
    owner_id: '1',
    owner: mockUsers[0],
    approver_id: '1',
    value: 8500,
    currency: 'BRL',
    value_brl: 8500,
    periodicity: 'annual',
    renewal_date: '2025-06-15',
    payment_method: 'transfer',
    user_count: 120,
    status: 'in_review',
    created_at: '2024-03-10',
    updated_at: '2024-03-10',
  },
  {
    id: '4',
    service_name: 'Consultoria de Segurança',
    description: 'Auditoria de segurança anual',
    expense_type: 'one_time',
    category_id: '4',
    category: mockCategories[3],
    company_id: '2',
    company: mockCompanies[1],
    department_id: '4',
    department: mockDepartments[3],
    owner_id: '2',
    owner: mockUsers[1],
    approver_id: '1',
    value: 45000,
    currency: 'BRL',
    value_brl: 45000,
    payment_method: 'transfer',
    status: 'draft',
    created_at: '2024-04-01',
    updated_at: '2024-04-01',
  },
  {
    id: '5',
    service_name: 'Figma Enterprise',
    description: 'Ferramenta de design colaborativo',
    expense_type: 'recurring',
    category_id: '1',
    category: mockCategories[0],
    company_id: '2',
    company: mockCompanies[1],
    department_id: '5',
    department: mockDepartments[4],
    owner_id: '3',
    owner: mockUsers[2],
    approver_id: '1',
    value: 1200,
    currency: 'USD',
    value_brl: 6000,
    periodicity: 'annual',
    renewal_date: '2025-01-20',
    payment_method: 'credit_card',
    user_count: 15,
    status: 'cancellation_requested',
    created_at: '2024-01-20',
    updated_at: '2024-12-15',
  },
];

const currentMonthStr = `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}-01`;

export const mockValidations: ExpenseValidation[] = [
  { id: '1', expense_id: '1', validator_id: '2', validation_month: currentMonthStr, status: 'pending', created_at: '2025-01-01', expense: mockExpenses[0] },
  { id: '2', expense_id: '2', validator_id: '2', validation_month: currentMonthStr, status: 'pending', created_at: '2025-01-01', expense: mockExpenses[1] },
  { id: '3', expense_id: '3', validator_id: '2', validation_month: currentMonthStr, status: 'pending', created_at: '2025-01-01', expense: mockExpenses[2] },
  { id: '4', expense_id: '4', validator_id: '2', validation_month: currentMonthStr, status: 'pending', created_at: '2025-01-01', expense: mockExpenses[3] },
  { id: '5', expense_id: '5', validator_id: '2', validation_month: currentMonthStr, status: 'pending', created_at: '2025-01-01', expense: mockExpenses[4] },
];

export const mockAlerts: Alert[] = [
  { id: '1', alert_type: 'renewal_upcoming', title: 'Renovação Próxima', message: 'A despesa "Figma Enterprise" será renovada em 5 dias.', recipient_id: '1', channel: 'email', status: 'pending', expense_id: '5', created_at: '2025-01-15T10:00:00' },
  { id: '2', alert_type: 'validation_pending', title: 'Validação Pendente', message: 'Você tem 2 despesas aguardando validação para Janeiro/2025.', recipient_id: '1', channel: 'email', status: 'pending', created_at: '2025-01-10T09:00:00' },
  { id: '3', alert_type: 'expense_cancellation', title: 'Cancelamento Solicitado', message: 'O cancelamento da despesa "Figma Enterprise" foi solicitado.', recipient_id: '1', channel: 'email', status: 'read', expense_id: '5', created_at: '2025-01-05T14:30:00', read_at: '2025-01-05T16:00:00' },
  { id: '4', alert_type: 'validation_overdue', title: 'Validação Atrasada', message: 'A validação da despesa "AWS Cloud Services" está atrasada.', recipient_id: '2', channel: 'email', status: 'pending', expense_id: '1', created_at: '2025-01-20T08:00:00' },
];

export const mockDashboardStats: DashboardStats = {
  total_expenses_value: 72200,
  pending_validations: 2,
  unread_alerts: 3,
  active_expenses: 3,
};

export const delay = (ms: number = 300) => new Promise(resolve => setTimeout(resolve, ms));
